-- Platform telemetry raw facts. Tenant key is merchant_id + shop_id.
-- Dedup key is (merchant_id, shop_id, surface, event_id). No app_id / commercial_id.

CREATE TABLE IF NOT EXISTS platform_telemetry_event (
    merchant_id   BIGINT       NOT NULL,
    shop_id       BIGINT       NOT NULL,
    surface       VARCHAR(16)  COLLATE utf8mb4_0900_as_cs NOT NULL,
    event_id      VARCHAR(64)  COLLATE utf8mb4_0900_as_cs NOT NULL,
    event_type    VARCHAR(32)  COLLATE utf8mb4_0900_as_cs NOT NULL,
    event_name    VARCHAR(128) COLLATE utf8mb4_0900_as_cs NOT NULL,
    page          VARCHAR(255) COLLATE utf8mb4_0900_as_cs NOT NULL DEFAULT '',
    component     VARCHAR(128) COLLATE utf8mb4_0900_as_cs NOT NULL DEFAULT '',
    action        VARCHAR(64)  COLLATE utf8mb4_0900_as_cs NOT NULL DEFAULT '',
    biz_type      VARCHAR(64)  COLLATE utf8mb4_0900_as_cs NOT NULL DEFAULT '',
    biz_id        VARCHAR(64)  COLLATE utf8mb4_0900_as_cs NOT NULL DEFAULT '',
    session_id    VARCHAR(96)  COLLATE utf8mb4_0900_as_cs NOT NULL DEFAULT '',
    anonymous_id  VARCHAR(96)  COLLATE utf8mb4_0900_as_cs NOT NULL DEFAULT '',
    subject       VARCHAR(128) COLLATE utf8mb4_0900_as_cs NOT NULL DEFAULT '',
    client_ts     BIGINT       NOT NULL,
    occurred_at   DATETIME(3)  NOT NULL,
    received_at   DATETIME(3)  NOT NULL,
    schema_version INT         NOT NULL DEFAULT 1,
    live_context  JSON         NOT NULL,
    props         JSON         NOT NULL,
    state         JSON         NOT NULL,
    extra         JSON         NOT NULL,
    user_agent    VARCHAR(512) COLLATE utf8mb4_0900_as_cs NOT NULL DEFAULT '',
    ip            VARCHAR(64)  COLLATE utf8mb4_0900_as_cs NOT NULL DEFAULT '',
    referer       VARCHAR(512) COLLATE utf8mb4_0900_as_cs NOT NULL DEFAULT '',
    ad_touch_id   BIGINT       NOT NULL DEFAULT 0,
    click_id_type VARCHAR(32)  COLLATE utf8mb4_0900_as_cs NOT NULL DEFAULT '',
    created_at    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (merchant_id, shop_id, surface, event_id),
    KEY idx_telemetry_client_ts (client_ts, event_id),
    KEY idx_telemetry_shop_time (merchant_id, shop_id, client_ts),
    KEY idx_telemetry_name (event_name, client_ts),
    CONSTRAINT ck_telemetry_ids CHECK (merchant_id > 0 AND shop_id > 0),
    CONSTRAINT ck_telemetry_surface CHECK (surface IN ('shop', 'merch', 'admin', 'live')),
    CONSTRAINT ck_telemetry_schema CHECK (schema_version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
