package model

import (
	"fmt"
	"net/url"
	"strings"
)

type RenderInput struct {
	Domains   DomainBase
	ACMEEmail string
	AskOrigin string
	Grant     string
	Upstreams map[string]string
}

func RenderCaddyfile(input RenderInput) (string, error) {
	fields := []struct{ label, host string }{
		{"平台主域名(root_domain)", input.Domains.RootDomain},
		{"商城域名(shop_domain)", input.Domains.ShopDomain},
		{"商户后台域名(merchant_domain)", input.Domains.MerchantDomain},
		{"直播间域名(live_domain)", input.Domains.LiveDomain},
		{"推流端域名(rts_domain)", input.Domains.RTSDomain},
		{"总后台域名(admin_domain)", input.Domains.AdminDomain},
	}
	seen := map[string]string{}
	for _, field := range fields {
		if field.host == "" {
			return "", fmt.Errorf("%s 不能为空", field.label)
		}
		if _, err := NormalizeHost(field.host); err != nil {
			return "", fmt.Errorf("%s 不是合法域名: %q", field.label, field.host)
		}
		if prev, dup := seen[field.host]; dup {
			return "", fmt.Errorf("%s 与 %s 重复: %q", field.label, prev, field.host)
		}
		seen[field.host] = field.label
	}
	for _, target := range []string{TargetShop, TargetLive, TargetMerch, TargetAdmin, TargetRTS, TargetGateway} {
		if strings.TrimSpace(input.Upstreams[target]) == "" {
			return "", fmt.Errorf("edge upstream %s is required", target)
		}
	}
	email := strings.TrimSpace(input.ACMEEmail)
	if email == "" || !strings.Contains(email, "@") {
		return "", fmt.Errorf("acme email is required")
	}
	ask, err := askURL(input.AskOrigin, input.Grant)
	if err != nil {
		return "", err
	}
	d := input.Domains
	u := input.Upstreams
	var b strings.Builder
	fmt.Fprintf(&b, `# Generated by Platform domain-base save. Do not edit; extra sites belong in extra/*.caddy.
{
  email %s
  admin :2019
  on_demand_tls {
    ask %s
  }
}

%s {
  encode gzip
  reverse_proxy %s
}

%s {
  encode gzip
  reverse_proxy %s
}

%s {
  encode gzip
  reverse_proxy %s
}

%s {
  encode gzip
  reverse_proxy %s
}

%s {
  encode gzip
  reverse_proxy %s
}

*.%s {
  tls {
    on_demand
  }
  encode gzip
  reverse_proxy %s
}

https:// {
  tls {
    on_demand
  }
  encode gzip
  reverse_proxy %s
}

import /etc/caddy/extra/*.caddy
`, email, ask, d.ShopDomain, u[TargetShop], d.MerchantDomain, u[TargetMerch], d.AdminDomain, u[TargetAdmin], d.RTSDomain, u[TargetRTS], d.LiveDomain, u[TargetLive], d.RootDomain, u[TargetGateway], u[TargetGateway])
	return b.String(), nil
}

func askURL(origin, grant string) (string, error) {
	origin = strings.TrimRight(strings.TrimSpace(origin), "/")
	if origin == "" {
		return "", fmt.Errorf("edge ask origin is required")
	}
	parsed, err := url.Parse(origin)
	if err != nil || parsed.Scheme == "" || parsed.Host == "" {
		return "", fmt.Errorf("edge ask origin is invalid")
	}
	query := url.Values{}
	if strings.TrimSpace(grant) != "" {
		query.Set("grant", grant)
	}
	parsed.Path = "/internal/platform/edge/hosts/allowed"
	parsed.RawQuery = query.Encode()
	return parsed.String(), nil
}
