name: liveshop-platform-test
services:
  platform:
    image: ${LIVESHOP_IMAGE_PREFIX}/backend:${LIVESHOP_IMAGE_TAG}
    build: !reset null
    ports: !override ["127.0.0.1:18082:18082", "127.0.0.1:19082:19082"]
  platform-control-admin:
    image: ${LIVESHOP_IMAGE_PREFIX}/frontend-admin:${LIVESHOP_IMAGE_TAG}
    build: !reset null
    ports: !override ["192.168.5.140:15180:18080"]
