name: liveshop-platform-test
services:
  grpc-certs:
    image: ${LIVESHOP_IMAGE_PREFIX}/backend:${LIVESHOP_IMAGE_TAG}
    build: !reset null
  platform:
    image: ${LIVESHOP_IMAGE_PREFIX}/backend:${LIVESHOP_IMAGE_TAG}
    build: !reset null
    ports: !override ["127.0.0.1:18082:8082", "127.0.0.1:9082:9082"]
  platform-control-admin:
    image: ${LIVESHOP_IMAGE_PREFIX}/frontend-admin:${LIVESHOP_IMAGE_TAG}
    build: !reset null
    ports: !override ["192.168.5.140:5180:8080"]
